import all from './all';
import any from './any';
import asyncFunction from './asyncFunction';
import array from './array';
import arrayLike from './arrayLike';
import arrayOf from './arrayOf';
import blank from './blank';
import boolean from './boolean';
import date from './date';
import defined from './defined';
import divisible from './divisible';
import divisibleWithRemainder from './divisibleWithRemainder';
import empty from './empty';
import emptyArray from './emptyArray';
import endsWith from './endsWith';
import equal from './equal';
import isFalse from './false';
import falsy from './falsy';
import finite from './finite';
import isFunction from './function';
import generator from './generator';
import greaterThan from './greaterThan';
import greaterThanOrEqual from './greaterThanOrEqual';
import hasOwnProperty from './hasOwnProperty';
import hasProperty from './hasProperty';
import isIn from './in';
import instanceOf from './instanceOf';
import integer from './integer';
import lessThan from './lessThan';
import lessThanOrEqual from './lessThanOrEqual';
import matches from './matches';
import map from './map';
import notANumber from './nan';
import negative from './negative';
import notBlank from './notBlank';
import notEmptyArray from './notEmptyArray';
import isNull from './null';
import isNumber from './number';
import isObject from './object';
import objectOf from './objectOf';
import oneOf from './oneOf';
import plainObject from './plainObject';
import positive from './positive';
import primitive from './primitive';
import property from './property';
import thenable from './thenable';
import regexp from './regexp';
import set from './set';
import startsWith from './startsWith';
import strictEqual from './startsWith';
import string from './string';
import structure from './structure';
import symbol from './symbol';
import isTrue from './true';
import truthy from './truthy';
import isUndefined from './undefined';
import undefinedOr from './undefinedOr';
import weakMap from './weakMap';
import weakSet from './weakSet';
import not from './not';

export {all, all as and};
export {any, any as or};
export {array, array as arr};
export {asyncFunction, asyncFunction as asyncFn};
export {arrayLike, arrayLike as arrLike};
export {arrayOf, arrayOf as arrOf};
export {blank};
export {boolean, boolean as bool};
export {date};
export {defined};
export {divisible, divisible as divisibleBy, divisible as divBy};
export {divisibleWithRemainder, divisible as divisibleByWithRemainder, divisible as divByWithRemainder};
export {empty};
export {emptyArray, emptyArray as emptyArr};
export {endsWith};
export {equal, equal as equalTo, equal as eq}

export {isFalse as false};
export {falsy, falsy as falsey};
export {finite};
export {isFunction as function, isFunction as fn, isFunction as func};
export {generator};
export {greaterThan, greaterThan as greater, greaterThan as gt};
export {
    greaterThanOrEqual,
    greaterThanOrEqual as greaterOrEqual,
    greaterThanOrEqual as greaterEq,
    greaterThanOrEqual as gtEq
};
export {hasOwnProperty, hasOwnProperty as hasOwn};
export {hasProperty, hasProperty as has};
export {isIn as in};
export {instanceOf, instanceOf as instance};
export {integer, integer as int};
export {lessThan, lessThan as less, lessThan as lt};
export {lessThanOrEqual, lessThanOrEqual as lessOrEqual, lessThanOrEqual as lessEq, lessThanOrEqual as ltEq};
export {matches, matches as match};
export {map};
export {notANumber, notANumber as nan, notANumber as NaN};
export {negative};
export {not as negate};
export {notBlank};
export {notEmptyArray, notEmptyArray as notEmptyArr};
export {isNull as null};
export {isNumber, isNumber as num};
export {isObject as object, isObject as obj};
export {objectOf, objectOf as objOf};
export {oneOf};
export {plainObject};
export {positive};
export {primitive};
export {property, property as prop};
export {regexp, regexp as regExp};
export {startsWith};
export {set};
export {strictEqual, strictEqual as strictEqualTo};
export {string, string as str};
export {structure, structure as struct};
export {symbol};
export {isTrue as true};
export {truthy};
export {thenable, thenable as promiseLike};
export {isUndefined as undefined};
export {undefinedOr};
export {weakMap};
export {weakSet};